### ISSUE TITLE
dev-ml is not Machine Learning - in ::gentoo it packages for OCaml :)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [MrPenguin07/ebuilds#4]
https://github.com/gentoo/guru/commit/7a33665aae8f672c7013b6e1939eece68f77b3af#commitcomment-143526392

**Comment by MrPenguin07** [comment]
Makes sense from an abbreviation perspective.
There are no "AI" categories in gentoo, and besides something vague like "net-misc" as suggested I am happy to leave this as is thanks.

**Comment by xgqt** [comment]
Hello, didn't think anybody else would have filed a issue like this before me that's why I made one myself [1].

I don't think there any rules for redefining a abbreviation but when anybody wanted to peek the metadata of category they would see this [2] - quote: "The dev-ml category contains libraries and utilities relevant to the ML programming language."
**So** in order to stay consistent you should also redefine this metadata for your repo...

But please let's not get into a war around what `dev-ml` should mean. 

The AI tools are becoming more and more popular and probably there will be time for that category in ::gentoo. That category name will definitely **not** include `-ml` and be more like `app-ai` or `dev-ai`. Other Gentoo devs would probably disagree about creating its own category and push to put AI tools into `dev-libs` and `dev-util`.

> There are no "AI" categories in gentoo

You can make one up.

Howto:

```shell
echo app-ai >> profiles/categories
mkdir app-ai
mv dev-ml/* app-ai/
```

Also, we have overlay maintainers who complied with my request, see [3].

See also:
* [1] https://github.com/MrPenguin07/ebuilds/issues/8 ("revoked" bug that I filed)
* [2] https://github.com/gentoo/gentoo/blob/master/dev-ml/metadata.xml
* [3] https://github.com/arran4/arrans_overlay/issues/8 (overlay maintainer complied)
